export const styles = {
    section: { marginBottom: 20 },
    sectionHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 14,
        flexWrap: "wrap",
        gap: 12,
    },
    tabsRow: {
        display: "flex",
        gap: 6,
        flexWrap: "wrap",
    },
    tabButton: {
        padding: "7px 14px",
        borderRadius: 999,
        border: "1px solid #d1d5db",
        backgroundColor: "#fff",
        color: "#374151",
        fontSize: 13,
        fontWeight: 500,
        cursor: "pointer",
        fontFamily: "system-ui, sans-serif",
    },
    tabButtonActive: {
        backgroundColor: "#2563eb",
        borderColor: "#2563eb",
        color: "#fff",
    },
    table: {
        width: "100%",
        borderCollapse: "collapse",
        fontFamily: "system-ui, sans-serif",
        fontSize: 14,
    },
    th: {
        padding: "10px 14px",
        textAlign: "left",
        borderBottom: "2px solid #ccc",
        backgroundColor: "#f5f5f5",
        fontWeight: 600,
        textTransform: "uppercase",
        fontSize: 12,
        letterSpacing: "0.03em",
    },
    td: {
        padding: "10px 14px",
        textAlign: "left",
        borderBottom: "1px solid #e0e0e0",
        verticalAlign: "top",
    },
    actionTd: {
        padding: "10px 14px",
        textAlign: "center",
        borderBottom: "1px solid #e0e0e0",
        width: 40,
        verticalAlign: "top",
    },
    editButton: {
        background: "none",
        border: "none",
        cursor: "pointer",
        fontSize: 15,
        padding: 4,
        borderRadius: 4,
    },
    addIconButton: {
        width: 30,
        height: 30,
        borderRadius: "50%",
        border: "none",
        backgroundColor: "#2563eb",
        color: "#fff",
        fontSize: 18,
        lineHeight: "30px",
        textAlign: "center",
        cursor: "pointer",
        padding: 0,
        flexShrink: 0,
    },
    promoBadges: {
        display: "flex",
        flexWrap: "wrap",
        gap: 6,
    },
    badge: {
        display: "inline-flex",
        alignItems: "center",
        gap: 4,
        padding: "4px 10px",
        backgroundColor: "#eef2ff",
        color: "#3730a3",
        borderRadius: 999,
        fontSize: 12,
        fontWeight: 500,
        cursor: "pointer",
        border: "1px solid #c7d2fe",
    },
    badgeCount: {
        backgroundColor: "#3730a3",
        color: "#fff",
        borderRadius: 999,
        fontSize: 11,
        padding: "1px 6px",
    },
    emptyBadgeNote: {
        fontSize: 12,
        color: "#999",
        fontStyle: "italic",
    },
    statusPill: {
        display: "inline-block",
        padding: "3px 10px",
        borderRadius: 999,
        fontSize: 12,
        fontWeight: 600,
        cursor: "pointer",
        border: "none",
    },
    statusActive: { backgroundColor: "#dcfce7", color: "#166534" },
    statusInactive: { backgroundColor: "#f3f4f6", color: "#6b7280" },
    overlay: {
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0,0,0,0.4)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1000,
    },
    modal: {
        backgroundColor: "#fff",
        borderRadius: 8,
        padding: 24,
        width: 360,
        boxShadow: "0 10px 30px rgba(0,0,0,0.2)",
        fontFamily: "system-ui, sans-serif",
    },
    modalTitle: {
        margin: "0 0 16px 0",
        fontSize: 16,
        fontWeight: 600,
    },
    field: {
        marginBottom: 12,
        display: "flex",
        flexDirection: "column",
        gap: 4,
    },
    label: {
        fontSize: 12,
        fontWeight: 600,
        color: "#555",
    },
    input: {
        padding: "8px 10px",
        border: "1px solid #ccc",
        borderRadius: 4,
        fontSize: 14,
    },
    select: {
        padding: "8px 10px",
        border: "1px solid #ccc",
        borderRadius: 4,
        fontSize: 14,
        backgroundColor: "#fff",
    },
    checkboxRow: {
        display: "flex",
        alignItems: "center",
        gap: 8,
        marginBottom: 16,
        fontSize: 14,
    },
    modalActions: {
        display: "flex",
        justifyContent: "flex-end",
        gap: 8,
        marginTop: 16,
    },
    cancelButton: {
        padding: "8px 14px",
        backgroundColor: "#f0f0f0",
        border: "none",
        borderRadius: 6,
        cursor: "pointer",
    },
    submitButton: {
        padding: "8px 14px",
        backgroundColor: "#2563eb",
        color: "#fff",
        border: "none",
        borderRadius: 6,
        cursor: "pointer",
    },
    eleveList: {
        listStyle: "none",
        margin: "0 0 16px 0",
        padding: 0,
        maxHeight: 180,
        overflowY: "auto",
    },
    eleveItem: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        padding: "6px 4px",
        borderBottom: "1px solid #f0f0f0",
        fontSize: 14,
    },
    removeEleveButton: {
        background: "none",
        border: "none",
        color: "#b91c1c",
        cursor: "pointer",
        fontSize: 13,
    },
    addEleveRow: {
        display: "flex",
        gap: 6,
    },
    emptyText: {
        fontSize: 13,
        color: "#888",
        fontStyle: "italic",
        margin: "0 0 12px 0",
    },
};